@echo off
setlocal

set "PATH=E:\tools\go\bin;C:\Program Files\Git\cmd;%PATH%"
set RANDOM_MIN_MINUTES_BETWEEN_COMMITS=240
set RANDOM_MAX_MINUTES_BETWEEN_COMMITS=480
set BOOST_RANDOM_MIN_MINUTES_BETWEEN_COMMITS=120
set BOOST_RANDOM_MAX_MINUTES_BETWEEN_COMMITS=360
set BOOST_FIXED_DATES=01-01,04-21,05-01,09-07,10-12,11-02,11-15,11-20,12-25
set BOOST_DATES=
set SAFETY_MAX_MINUTES_WITHOUT_COMMIT=1200
set MAX_COMMITS_PER_DAY=10
set COMMIT_DAY_TIMEZONE=America/Sao_Paulo
set HEARTBEAT_FILE=.daily-commit\heartbeat.json
set SOURCE_TEXT_FILE=meu roteiro.txt
set OUTPUT_TEXT_FILE=roteiro.md
set WORD_STATE_FILE=.daily-commit\word-state.json
set TARGET_BRANCH=main
set FORCE_COMMIT=true
set SKIP_PUSH=true

go run .\scripts\daily_commit.go
